name: Build Node.js Cache

on:
  push:
    branches:
      - '*'
      - '**'
      - '*/*'

permissions:
  contents: write
  discussions: write

jobs:
  load-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.load.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - id: load
        shell: bash
        run: |
          echo "matrix=$(jq -c . matrix.json)" >> "$GITHUB_OUTPUT"

  build:
    needs: load-matrix

    env:
      ACTIONS_STEP_DEBUG: true

    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.load-matrix.outputs.matrix) }}

    runs-on: ${{ matrix.target.runner }}

    steps:
      - name: Checkout actions
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare-environment
        with:
          node_version: ${{ matrix.node_version }}
          os: ${{ matrix.target.os }}
          arch: ${{ matrix.target.arch }}
          runner: ${{ matrix.target.runner }}

      - name: Configure (Linux/Darwin)
        working-directory: node
        if: ${{ matrix.target.os != 'windows' }}
        run: |
          ./configure $BUILD_ARGS

      - name: Make (Linux/Darwin)
        working-directory: node
        if: ${{ matrix.target.os != 'windows' }}
        run: |
          make -j$JOBS

      - name: Build (Windows)
        if: ${{ matrix.target.os == 'windows' }}
        working-directory: node
        run: |
          cmd /c "vcbuild.bat ${{ matrix.target.arch }} full-icu ccache %GITHUB_WORKSPACE%\ccache-bin"

      - name: Package build cache
        shell: bash
        run: |
          mkdir artifact
          ls -al
          mv node artifact/ || true
          ls -al .ccache || true
          mv .ccache artifact/ || true

      - name: Create archive
        shell: bash
        run: |
          tar -czf node-${{ matrix.node_version }}-${{ matrix.target.os }}-${{ matrix.target.arch }}.tar.gz artifact
          ls -lh *.tar.gz

      - name: Split package
        shell: bash
        run: |
          split -b 1900M node-${{ matrix.node_version }}-${{ matrix.target.os }}-${{ matrix.target.arch }}.tar.gz node-${{ matrix.node_version }}-${{ matrix.target.os }}-${{ matrix.target.arch }}.tar.gz.part.
          ls -lh *.part.*

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: Build ${{ github.run_id }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: build-${{ github.run_id }}
          make_latest: true
          files: |
            node-${{ matrix.node_version }}-${{ matrix.target.os }}-${{ matrix.target.arch }}.tar.gz.part.*
