name: Build Node.js Cache

on:
  push:
    branches:
      - '*'
      - '**'
      - '*/*'

jobs:
  build-linux-standard-and-static-libc-arm64:
    strategy:
      matrix:
        node_version: ["24.16.0"]
        target:
          - { os: "linux", arch: "arm64", runner: "ubuntu-24.04-arm" }
          - { os: "alpine", arch: "arm64", runner: "ubuntu-24.04-arm" }
          - { os: "linuxstatic", arch: "arm64", runner: "ubuntu-24.04-arm" }

    runs-on: ${{ matrix.target.runner }}

    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            python3 \
            curl \
            ccache \
            pkg-config \
            brotli \
            musl-tools

      - uses: ./.github/actions/build-node-cache
        with:
          node_version: ${{ matrix.node_version }}
          os: ${{ matrix.target.os }}
          arch: ${{ matrix.target.arch }}
          token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.run_id }}
          ccache_dir: ${{ env.CCACHE_DIR }}

  build-linux-static-libc-x64:
    strategy:
      matrix:
        node_version: ["24.16.0"]
        target:
          - { os: "alpine", arch: "x64", runner: "ubuntu-24.04" }
          - { os: "linuxstatic", arch: "x64", runner: "ubuntu-24.04" }

    runs-on: ${{ matrix.target.runner }}

    container:
      image: alpine:3.22

    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache \
            brotli \
            build-base \
            python3 \
            linux-headers \
            bash \
            pkgconf \
            curl \
            ccache

      - uses: ./.github/actions/build-node-cache
        with:
          node_version: ${{ matrix.node_version }}
          os: ${{ matrix.target.os }}
          arch: ${{ matrix.target.arch }}
          token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.run_id }}
          ccache_dir: ${{ env.CCACHE_DIR }}

  release:
    needs:
      - build-linux-standard-and-static-libc-arm64
      - build-linux-static-libc-x64

    strategy:
      matrix:
        node_version: ["24.16.0"]
        target:
          - { os: "linux", arch: "arm64", runner: "ubuntu-24.04-arm" }
          - { os: "alpine", arch: "arm64", runner: "ubuntu-24.04-arm" }
          - { os: "linuxstatic", arch: "arm64", runner: "ubuntu-24.04-arm" }

    runs-on: ubuntu

    steps:
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          key: ${{ github.run_id }}-${{ matrix.node_version }}-${{ matrix.target.os }}-${{ matrix.target.arch }}
          path: node-${{ matrix.node_version }}-${{ matrix.target.os }}-${{ matrix.target.arch }}.tar.br

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_name == 'master'
        with:
          files: |
            ./*.tar.br
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: build-${{ github.run_id }}
          name: Build ${{ github.run_id }}
