name: Build Cache Images

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

permissions:
  contents: read
  packages: write
  repository-projects: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        target:
          - { os: linux,   arch: amd64, libc: gnu  }
          # - { os: linux,   arch: arm64, libc: gnu  }
          # - { os: linux,   arch: amd64, libc: musl }
          # - { os: linux,   arch: arm64, libc: musl }
          # - { os: windows, arch: amd64, libc: gnu  }
          # - { os: windows, arch: arm64, libc: gnu  }
          # - { os: darwin,  arch: amd64, libc: gnu  }
          # - { os: darwin,  arch: arm64, libc: gnu  }

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check project
        run: ls -al

      # - name: Login to Aliyun Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ secrets.ALIYUN_REGISTRY }}
      #     username: ${{ secrets.ALIYUN_USERNAME }}
      #     password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Prepare
        id: info
        run: |
          # curl -L -o ./base/sdks/MacOSX15.5.sdk.tar.xz https://github.com/joseluisq/macosx-sdks/releases/download/15.5/MacOSX15.5.sdk.tar.xz
          echo "latest_version=$(curl -fsSL https://api.github.com/repos/nodejs/node/releases/latest | jq -r .tag_name)" >> "$GITHUB_OUTPUT"

      - name: Build
        run: |
          docker build \
            --build-arg TARGET_OS=${{ matrix.target.os }} \
            --build-arg TARGET_ARCH=${{ matrix.target.arch }} \
            --build-arg TARGET_LIBC=${{ matrix.target.libc }} \
            --build-arg NODE_VERSION=${{ startsWith(github.ref_name, 'v') && github.ref_name || steps.info.outputs.latest_version }} \
            -t ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/node-build-cache:${{ github.ref_name }}-${{ matrix.target.os }}-${{ matrix.target.arch }}-${{ matrix.target.libc }} \
            -f Dockerfile .

      - name: Push to registry
        if: startsWith(github.ref_name, 'v')
        run: |
          docker push ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/node-build-cache:${{ github.ref_name }}-${{ matrix.target.os }}-${{ matrix.target.arch }}-${{ matrix.target.libc }}
