name: Build Node.js Cache

on:
  push:
    branches:
      - '*'
      - '**'
      - '*/*'

jobs:
  build-linux:
    strategy:
      matrix:
        node_version: ["24.16.0"]
        target:
          - { os: "linux", arch: "x64", runner: "ubuntu-24.04" }
          - { os: "linux", arch: "arm64", runner: "ubuntu-24.04-arm" }
          - { os: "alpine", arch: "x64", runner: "ubuntu-24.04" }
          - { os: "alpine", arch: "arm64", runner: "ubuntu-24.04-arm" }
          - { os: "linuxstatic", arch: "x64", runner: "ubuntu-24.04" }
          - { os: "linuxstatic", arch: "arm64", runner: "ubuntu-24.04-arm" }

    runs-on: ${{ matrix.target.runner }}

    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            python3 \
            curl \
            ccache \
            pkg-config \
            brotli \
            musl-tools

      - name: Checkout Node.js Source Code
        shell: bash
        run: |
          curl -L -o node.tar.gz \
            https://github.com/nodejs/node/archive/refs/tags/v${{ matrix.node_version }}.tar.gz
          tar -zxf node.tar.gz
          mv node-${{ matrix.node_version }} node
          rm node.tar.gz

      - name: Setup ccache
        shell: bash
        run: |
          mkdir -p "${{ env.CCACHE_DIR }}"
          ccache --set-config=max_size=10G
          ccache --zero-stats

      - name: Setup MUSL ARM64
        shell: bash
        if: ${{ (matrix.target.os == 'alpine' || matrix.target.os == 'linuxstatic') && matrix.target.arch == 'arm64' }}
        run: |
          curl -LO https://github.com/troglobit/misc/releases/download/11-20211120/aarch64-linux-musl-cross.tgz
          tar zvf aarch64-linux-musl-cross.tgz
          rm -rf aarch64-linux-musl-cross.tgz

      - name: Setup MUSL x64
        shell: bash
        if: ${{ (matrix.target.os == 'alpine' || matrix.target.os == 'linuxstatic') && matrix.target.arch == 'x64' }}
        run: |
          curl -LO https://github.com/troglobit/misc/releases/download/11-20211120/x86_64-linux-musl-cross.tgz
          tar zvf x86_64-linux-musl-cross.tgz
          rm -rf x86_64-linux-musl-cross.tgz

      - name: Configure
        shell: bash
        env:
          OS: ${{ matrix.target.os }}
        working-directory: node
        run: |
          export PATH="./aarch64-linux-musl-cross/bin:./x86_64-linux-musl-cross/bin:$PATH"
          BUILD_ARGS="--enable-lto --without-inspector --without-npm --without-intl"
          case "$OS" in
            linuxstatic)
              BUILD_ARGS="$BUILD_ARGS --fully-static"
              ;;
            alpine)
              BUILD_ARGS="$BUILD_ARGS --partly-static"
              ;;
          esac
          if [[ ("$OS" == "alpine" || "$OS" == "linuxstatic")  && "$ARCH" == "arm64" ]]; then
            case "$OS" in
              linuxstatic)
                export CC="aarch64-linux-musl-gcc -static"
                export CXX="aarch64-linux-musl-g++ -static"
                ;;
              alpine)
                export CC=aarch64-linux-musl-gcc
                export CXX=aarch64-linux-musl-g++
                ;;
            esac
            export AR=aarch64-linux-musl-ar
            export RANLIB=aarch64-linux-musl-ranlib
          fi
          if [[ ("$OS" == "alpine" || "$OS" == "linuxstatic")  && "$ARCH" == "x64" ]]; then
            case "$OS" in
              linuxstatic)
                export CC="x86_64-linux-musl-gcc -static"
                export CXX="x86_64-linux-musl-g++ -static"
                ;;
              alpine)
                export CC=x86_64-linux-musl-gcc
                export CXX=x86_64-linux-musl-g++
                ;;
            esac
            export AR=x86_64-linux-musl-ar
            export RANLIB=x86_64-linux-musl-ranlib
          fi
          ./configure $BUILD_ARGS

      - name: Build
        shell: bash
        working-directory: node
        run: |
          make -j$(nproc)

      - name: Show ccache stats
        shell: bash
        run: |
          ccache --show-stats

      - name: Package build cache
        shell: bash
        run: |
          mkdir artifact
          cp -r node artifact/node
          cp -r .ccache artifact/.ccache

      - name: Create archive
        shell: bash
        run: |
          tar -cf - artifact | brotli > node-${{ matrix.node_version }}-${{ matrix.target.os }}-${{ matrix.target.arch }}.tar.br

      - name: Upload Cache
        uses: actions/cache@v4
        with:
          key: ${{ github.run_id }}-${{ matrix.node_version }}-${{ matrix.target.os }}-${{ matrix.target.arch }}
          path: node-${{ matrix.node_version }}-${{ matrix.target.os }}-${{ matrix.target.arch }}.tar.br

  # build-windows:
  #   strategy:
  #     matrix:
  #       node_version: ["24.16.0"]
  #       target:
  #         - { os: "windows", arch: "x64", runner: "windows-latest" }
  #         - { os: "windows", arch: "arm64", runner: "windows-11-arm" }

  #   runs-on: ${{ matrix.target.runner }}

  #   env:
  #     CCACHE_DIR: ${{ github.workspace }}/.ccache

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v6
  #       with:
  #         python-version: '3.12'
  #         check-latest: true

  #     - run: choco install nasm

  #     - uses: ./.github/actions/build-node-cache
  #       with:
  #         node_version: ${{ matrix.node_version }}
  #         os: ${{ matrix.target.os }}
  #         arch: ${{ matrix.target.arch }}
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         run_id: ${{ github.run_id }}
  #         ccache_dir: ${{ env.CCACHE_DIR }}

  aggregation-artifacts:
    needs:
      - build-linux-standard-and-static-libc-arm64
      - build-linux-static-libc-x64

    strategy:
      matrix:
        node_version: ["24.16.0"]
        target:
          - { os: "linux", arch: "arm64", runner: "ubuntu-24.04-arm" }
          - { os: "alpine", arch: "arm64", runner: "ubuntu-24.04-arm" }
          - { os: "linuxstatic", arch: "arm64", runner: "ubuntu-24.04-arm" }

    runs-on: ubuntu

    steps:
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          key: ${{ github.run_id }}-${{ matrix.node_version }}-${{ matrix.target.os }}-${{ matrix.target.arch }}
          path: node-${{ matrix.node_version }}-${{ matrix.target.os }}-${{ matrix.target.arch }}.tar.br

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_name == 'master'
        with:
          files: |
            ./*.tar.br
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: build-${{ github.run_id }}
          name: Build ${{ github.run_id }}
